export const SESSION_TTL = 30 * 60 * 1000;

export const STATES = {
  WELCOME: "WELCOME",
  REGISTER_NAME: "REGISTER_NAME",
  REGISTER_ADDRESS: "REGISTER_ADDRESS",
  SHOW_CATALOG: "SHOW_CATALOG",
  SELECT_PRODUCT: "SELECT_PRODUCT",
  CONFIRM_ORDER: "CONFIRM_ORDER",
} as const;
